//
//  AppIconPicker.swift
//  Raul
//
//  Alternate app icon selection for the settings screen.
//

import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

/// One selectable app icon.
///
/// `alternateName` is `nil` for the icon shipped as the primary `AppIcon`, which is
/// what `UIApplication.setAlternateIconName(_:)` expects in order to restore the default.
struct MovesAppIcon: Identifiable, Hashable {
    let id: String
    let alternateName: String?

    static let primary = MovesAppIcon(id: "AppIcon", alternateName: nil)

    /// One entry per `.icon` bundle in `Moves/Icons`. The names come from
    /// `GeneratedAppIcons.swift`, which `Scripts/generate-icon-previews.sh` rewrites at the
    /// start of every build, so adding an icon to that folder is all it takes to list it here.
    static let alternates: [MovesAppIcon] = generatedAlternateNames.map {
        MovesAppIcon(id: $0, alternateName: $0)
    }

    static let all: [MovesAppIcon] = [primary] + alternates

    /// Artwork for the picker.
    ///
    /// The compiled app icons themselves cannot be used here: they land in the asset
    /// catalog as multi-size icon stacks, and `UIImage(named:)` raises "Need an imageRef"
    /// on those. `Moves/Assets.xcassets/iconPreviews` holds a flat image per icon instead,
    /// also generated by `Scripts/generate-icon-previews.sh`.
    var previewAssetName: String { "iconPreviews/\(id)" }

    var hasPreviewAsset: Bool { UIImage(named: previewAssetName) != nil }
}

@MainActor
@Observable
final class AppIconStore {
    private(set) var selected: MovesAppIcon
    var errorMessage: String?
    var isShowingError = false

    /// Alternate icons are unavailable on a few platforms, so the picker can hide
    /// itself rather than offer a switch that always fails.
    let isSupported: Bool

    init() {
        let application = UIApplication.shared
        isSupported = application.supportsAlternateIcons

        let currentName = application.alternateIconName
        selected = MovesAppIcon.all.first { $0.alternateName == currentName } ?? .primary
    }

    func select(_ icon: MovesAppIcon) {
        guard icon != selected else { return }

        let previous = selected
        selected = icon

        UIApplication.shared.setAlternateIconName(icon.alternateName) { [weak self] error in
            Task { @MainActor in
                guard let self, let error else { return }
                self.selected = previous
                self.errorMessage = error.localizedDescription
                self.isShowingError = true
            }
        }
    }
}

/// The row in Settings that opens the picker. Shows the icon that is currently in use, so
/// the card says what it needs to without a caption.
struct AppIconPickerSection: View {
    @State private var store = AppIconStore()

    var body: some View {
        if store.isSupported {
            SettingsCard(title: "App Icon") {
                NavigationLink {
                    AppIconPickerView(store: store)
                } label: {
                    HStack(spacing: 12) {
                        AppIconTile(icon: store.selected, isSelected: false, size: 40)

                        Spacer(minLength: 8)

                        Image(systemName: "chevron.right")
                            .font(.footnote.weight(.semibold))
                            .foregroundStyle(.secondary)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .contentShape(Rectangle())
                    .padding(.vertical, 5)
                }
                .buttonStyle(.plain)
                .accessibilityLabel("App Icon")
                .accessibilityValue(store.selected.id)
            }
        }
    }
}

struct AppIconPickerView: View {
    @Environment(\.dismiss) private var dismiss

    @Bindable var store: AppIconStore

    private let columns = [GridItem(.adaptive(minimum: 64, maximum: 92), spacing: 14)]

    var body: some View {
        ScrollView {
            LazyVStack(spacing: 14) {
                LazyVGrid(columns: columns, spacing: 14) {
                    ForEach(MovesAppIcon.all) { icon in
                        Button {
                            store.select(icon)
                        } label: {
                            AppIconTile(icon: icon, isSelected: icon == store.selected)
                        }
                        .buttonStyle(.plain)
                        .accessibilityLabel(icon.id)
                        .accessibilityAddTraits(icon == store.selected ? [.isButton, .isSelected] : .isButton)
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .panelSurface()
            }
            .padding(.horizontal, 14)
            .padding(.top, 10)
            .padding(.bottom, 18)
        }
        .background {
            LinearGradient(
                colors: [MovesPalette.backgroundTop, MovesPalette.backgroundBottom],
                startPoint: .top,
                endPoint: .bottom
            )
            .ignoresSafeArea()
        }
        .navigationTitle("App Icon")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            ToolbarItem(placement: .topBarTrailing) {
                Button("Done") {
                    dismiss()
                }
            }
        }
        .alert("App Icon", isPresented: $store.isShowingError) {
            Button("OK", role: .cancel) {}
        } message: {
            Text(store.errorMessage ?? "")
        }
    }
}

private struct AppIconTile: View {
    let icon: MovesAppIcon
    let isSelected: Bool
    var size: CGFloat = 64

    // Matches the shape iOS draws app icons in, so a tile reads as an icon at any size.
    private var cornerRadius: CGFloat { size * 0.2237 }

    var body: some View {
        artwork
            .frame(width: size, height: size)
            .clipShape(RoundedRectangle(cornerRadius: cornerRadius, style: .continuous))
            .overlay {
                RoundedRectangle(cornerRadius: cornerRadius, style: .continuous)
                    .strokeBorder(
                        isSelected ? AnyShapeStyle(Color.accentColor) : AnyShapeStyle(.separator),
                        lineWidth: isSelected ? 3 : 1
                    )
            }
            .padding(3)
            .contentShape(Rectangle())
    }

    @ViewBuilder
    private var artwork: some View {
        if icon.hasPreviewAsset {
            Image(icon.previewAssetName)
                .resizable()
                .aspectRatio(contentMode: .fill)
        } else {
            RoundedRectangle(cornerRadius: cornerRadius, style: .continuous)
                .fill(.quaternary)
                .overlay {
                    Image(systemName: "app.dashed")
                        .font(.title3)
                        .foregroundStyle(.secondary)
                }
        }
    }
}
