#!/bin/bash
#
# Keeps everything that depends on the .icon bundles in Moves/Icons up to date:
#
#   * Moves/GeneratedAppIcons.swift       - the list the Settings picker iterates
#   * Moves/Info.plist                    - CFBundleAlternateIcons, so the icons can be selected
#   * Moves/Assets.xcassets/iconPreviews  - flat light/dark preview per icon, for the picker
#
# Runs as the first build phase of the Moves target, and can also be run by hand:
#
#     ./Scripts/generate-icon-previews.sh                 # fill in missing previews
#     ./Scripts/generate-icon-previews.sh --force NYC doom # regenerate these previews
#     ./Scripts/generate-icon-previews.sh --force         # regenerate every preview
#
# Drop a new Foo.icon into Moves/Icons, add it to the Moves target in Xcode so it gets
# compiled, and the next build picks it up everywhere. Nothing else to edit.
#
# Previews are only generated for icons that do not have an imageset yet. An existing
# imageset is never touched, so you can replace a generated preview with one exported from
# Icon Composer and it stays. To refresh a preview after redesigning its icon, delete the
# imageset or pass the icon name to --force.
#
# Why previews exist at all: app icons compile into the asset catalog as multi-size icon
# stacks. UIImage(named:) does not just fail on those, it raises "Need an imageRef", so the
# picker cannot draw the real icon assets and needs a flat copy of each one.
#
# The preview extraction reads composited renditions out of a compiled Assets.car through
# CoreUI, a private framework. That is fine for a tool that only ever runs on a Mac at build
# time, but it is not shipped in the app and a future Xcode could break it. If that happens
# the build fails with a clear message; export the icons from Icon Composer and drop the
# PNGs into the imagesets by hand until this is fixed.

set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"

ICONS_DIR="$ROOT/Moves/Icons"
PRIMARY_NAME="AppIcon"
PRIMARY_ICON="$ROOT/Moves/$PRIMARY_NAME.icon"
PREVIEWS="$ROOT/Moves/Assets.xcassets/iconPreviews"
GENERATED_SWIFT="$ROOT/Moves/GeneratedAppIcons.swift"
INFO_PLIST="$ROOT/Moves/Info.plist"

PREVIEW_SIZE=384

FORCE_ALL=0
FORCE_NAMES=()
if [ "${1:-}" = "--force" ]; then
    shift
    if [ $# -eq 0 ]; then FORCE_ALL=1; else FORCE_NAMES=("$@"); fi
fi

note() { echo "generate-icon-previews: $*"; }
fail() { echo "error: generate-icon-previews: $*" >&2; exit 1; }

icon_path() {
    if [ "$1" = "$PRIMARY_NAME" ]; then echo "$PRIMARY_ICON"; else echo "$ICONS_DIR/$1.icon"; fi
}

# --- Which icons are there? ------------------------------------------------------------

ALTERNATES=()
for icon in "$ICONS_DIR"/*.icon; do
    [ -d "$icon" ] || continue
    name="$(basename "$icon" .icon)"
    case "$name" in
        *" "*) fail "icon name \"$name\" contains a space; actool splits those into separate icons. Rename it." ;;
    esac
    ALTERNATES+=("$name")
done

if [ ${#ALTERNATES[@]} -eq 0 ]; then
    note "no .icon bundles in Moves/Icons; nothing to do"
    exit 0
fi

# An icon that is not a member of the Moves target never reaches Assets.car, so selecting it
# would fail at runtime even though everything here looks fine. Catch that at build time.
for name in "${ALTERNATES[@]}"; do
    if ! grep -q "$name.icon in Resources" "$ROOT/Moves.xcodeproj/project.pbxproj"; then
        echo "warning: $name.icon is not in the Moves target; add it in Xcode (File Inspector > Target Membership) or it will not be selectable"
    fi
done

for name in "${FORCE_NAMES[@]+"${FORCE_NAMES[@]}"}"; do
    [ -d "$(icon_path "$name")" ] || fail "--force $name: there is no $name.icon"
done

# --- 1. The list the picker iterates, and the Info.plist entries that make it work --------

# Cheap, and only writes files whose content changes, so it runs on every build.
/usr/bin/python3 - "$GENERATED_SWIFT" "$INFO_PLIST" "${ALTERNATES[@]}" <<'PY'
import plistlib, sys, pathlib

swift_path, plist_path, *names = sys.argv[1:]

swift = '''//
//  GeneratedAppIcons.swift
//  Raul
//
//  Generated by Scripts/generate-icon-previews.sh from the .icon bundles in Moves/Icons.
//  Do not edit; your changes will be overwritten on the next build.
//

extension MovesAppIcon {
    /// Every alternate icon that ships with the app, in Moves/Icons order.
    static let generatedAlternateNames: [String] = [
%s
    ]
}
''' % "\n".join('        "%s",' % name for name in names)

def write_if_changed(path, data):
    p = pathlib.Path(path)
    if p.exists() and p.read_bytes() == data:
        return
    p.write_bytes(data)

write_if_changed(swift_path, swift.encode())

# Update only the generated CFBundleIcons block. Re-serializing the complete plist would
# discard the C preprocessor directives used for platform-specific metadata.
from xml.sax.saxutils import escape

lines = pathlib.Path(plist_path).read_text().splitlines(keepends=True)
fragment = [
    "\t<key>CFBundleIcons</key>\n",
    "\t<dict>\n",
    "\t\t<key>CFBundleAlternateIcons</key>\n",
    "\t\t<dict>\n",
]
for name in names:
    escaped_name = escape(name)
    fragment.extend([
        f"\t\t\t<key>{escaped_name}</key>\n",
        "\t\t\t<dict>\n",
        "\t\t\t\t<key>CFBundleIconName</key>\n",
        f"\t\t\t\t<string>{escaped_name}</string>\n",
        "\t\t\t</dict>\n",
    ])
fragment.extend(["\t\t</dict>\n", "\t</dict>\n"])

key_index = next(
    (index for index, line in enumerate(lines) if line.strip() == "<key>CFBundleIcons</key>"),
    None,
)
if key_index is None:
    # Insert before the root dictionary's closing tag.
    end_index = max(index for index, line in enumerate(lines) if line.strip() == "</dict>")
    lines[end_index:end_index] = fragment
else:
    value_index = key_index + 1
    if value_index >= len(lines) or lines[value_index].strip() != "<dict>":
        raise RuntimeError("CFBundleIcons does not contain a dictionary in Info.plist")

    depth = 0
    end_index = None
    for index in range(value_index, len(lines)):
        stripped = lines[index].strip()
        if stripped == "<dict>":
            depth += 1
        elif stripped == "</dict>":
            depth -= 1
            if depth == 0:
                end_index = index + 1
                break
    if end_index is None:
        raise RuntimeError("Could not find the end of CFBundleIcons in Info.plist")
    lines[key_index:end_index] = fragment

write_if_changed(plist_path, "".join(lines).encode())
PY

# --- 2. Which previews need generating? --------------------------------------------------

forced() {
    [ "$FORCE_ALL" -eq 1 ] && return 0
    local name
    for name in "${FORCE_NAMES[@]+"${FORCE_NAMES[@]}"}"; do [ "$name" = "$1" ] && return 0; done
    return 1
}

PENDING=()
for name in "$PRIMARY_NAME" "${ALTERNATES[@]}"; do
    if forced "$name" || [ ! -d "$PREVIEWS/$name.imageset" ]; then
        PENDING+=("$name")
    fi
done

# Previews whose icon is gone are left alone, but worth knowing about.
for set in "$PREVIEWS"/*.imageset; do
    [ -d "$set" ] || continue
    name="$(basename "$set" .imageset)"
    [ -d "$(icon_path "$name")" ] || echo "warning: iconPreviews/$name has no matching .icon; delete it if the icon was removed"
done

[ ${#PENDING[@]} -gt 0 ] || exit 0

note "generating previews for: ${PENDING[*]}"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# --- 3. Composite the pending icons, then pull the renditions back out --------------------

mkdir -p "$WORK/car"
ICON_ARGS=()
for name in "${PENDING[@]}"; do ICON_ARGS+=("$(icon_path "$name")"); done

env -u SDKROOT -u PLATFORM_NAME xcrun actool "${ICON_ARGS[@]}" \
    --compile "$WORK/car" \
    --app-icon "${PENDING[0]}" \
    --include-all-app-icons \
    --output-partial-info-plist "$WORK/partial.plist" \
    --target-device iphone \
    --minimum-deployment-target 26.0 \
    --platform iphoneos \
    --output-format human-readable-text >/dev/null \
    || fail "actool could not compile the icon bundles"

cat > "$WORK/extract.m" <<'OBJC'
#import <Foundation/Foundation.h>
#import <AppKit/AppKit.h>
#import <dlfcn.h>

// Writes <name>~light.png and <name>~dark.png for each named icon in the catalog.
int main(int argc, char **argv) {
    if (argc < 4) { fprintf(stderr, "usage: extract <Assets.car> <outDir> <name>...\n"); return 2; }
    if (!dlopen("/System/Library/PrivateFrameworks/CoreUI.framework/CoreUI", RTLD_LAZY)) return 1;
    Class CUICatalog = NSClassFromString(@"CUICatalog");
    Class CUINamedImage = NSClassFromString(@"CUINamedImage");
    if (!CUICatalog || !CUINamedImage) return 1;

    NSError *error = nil;
    SEL initSel = NSSelectorFromString(@"initWithURL:error:");
    id allocated = [CUICatalog alloc];
    typedef id (*InitFn)(id, SEL, NSURL *, NSError **);
    NSURL *url = [NSURL fileURLWithPath:[NSString stringWithUTF8String:argv[1]]];
    id catalog = ((InitFn)[allocated methodForSelector:initSel])(allocated, initSel, url, &error);
    if (!catalog) return 1;

    NSString *outDir = [NSString stringWithUTF8String:argv[2]];
    [[NSFileManager defaultManager] createDirectoryAtPath:outDir
                              withIntermediateDirectories:YES attributes:nil error:nil];

    // Each icon comes back as several renditions: per idiom (phone, pad) and per appearance
    // (any, dark, tintable). Their order is not something to rely on - phone-light is followed
    // by pad-light, not by dark - so pick by the appearance each rendition reports.
    NSDictionary *wanted = @{ @"UIAppearanceAny": @"light", @"UIAppearanceDark": @"dark" };
    const long phoneIdiom = 1;

    for (int i = 3; i < argc; i++) {
        NSString *name = [NSString stringWithUTF8String:argv[i]];
        NSMutableDictionary *best = [NSMutableDictionary dictionary];

        for (id rep in [catalog performSelector:@selector(imagesWithName:) withObject:name]) {
            if (![rep isKindOfClass:CUINamedImage]) continue;
            CGImageRef image = (__bridge CGImageRef)[rep performSelector:@selector(image)];
            if (!image || CGImageGetWidth(image) < 512) continue;

            NSString *suffix = wanted[[[rep valueForKey:@"appearance"] description]];
            if (!suffix) continue;

            // Prefer the phone rendition; take another idiom only if there is no phone one.
            long idiom = (long)[rep performSelector:@selector(idiom)];
            if (best[suffix] && idiom != phoneIdiom) continue;
            best[suffix] = rep;
        }

        for (NSString *suffix in best) {
            CGImageRef image = (__bridge CGImageRef)[best[suffix] performSelector:@selector(image)];
            NSBitmapImageRep *bitmap = [[NSBitmapImageRep alloc] initWithCGImage:image];
            NSData *png = [bitmap representationUsingType:NSBitmapImageFileTypePNG properties:@{}];
            [png writeToFile:[NSString stringWithFormat:@"%@/%@~%@.png", outDir, name, suffix]
                  atomically:YES];
        }
    }
    return 0;
}
OBJC

# Xcode exports a target-SDK environment that leaks into clang and breaks a host compile,
# so build the helper in a scrubbed environment.
MAC_SDK="$(env -i PATH=/usr/bin:/bin DEVELOPER_DIR="${DEVELOPER_DIR:-}" \
    /usr/bin/xcrun --sdk macosx --show-sdk-path)"
env -i PATH=/usr/bin:/bin DEVELOPER_DIR="${DEVELOPER_DIR:-}" \
    /usr/bin/xcrun --sdk macosx clang -isysroot "$MAC_SDK" \
    -fno-objc-arc -framework Foundation -framework AppKit -framework CoreGraphics \
    -o "$WORK/extract" "$WORK/extract.m" -Wno-objc-method-access -Wno-deprecated-declarations \
    || fail "could not build the rendition extractor"

"$WORK/extract" "$WORK/car/Assets.car" "$WORK/png" "${PENDING[@]}" \
    || fail "could not read composited icons out of Assets.car (CoreUI may have changed)"

# --- 4. One namespaced imageset per pending icon -----------------------------------------

mkdir -p "$PREVIEWS"
if [ ! -f "$PREVIEWS/Contents.json" ]; then
    cat > "$PREVIEWS/Contents.json" <<'JSON'
{
  "info" : {
    "author" : "xcode",
    "version" : 1
  },
  "properties" : {
    "provides-namespace" : true
  }
}
JSON
fi

for name in "${PENDING[@]}"; do
    light="$WORK/png/$name~light.png"
    dark="$WORK/png/$name~dark.png"
    [ -f "$light" ] || fail "no composited artwork came back for \"$name\""
    if [ ! -f "$dark" ]; then
        echo "warning: $name.icon has no dark rendition; its preview uses the light artwork in dark mode"
        dark="$light"
    fi

    # Each imageset is built aside and moved into place, so a failure cannot leave a
    # half-written imageset that breaks the asset catalog.
    set="$WORK/stage/$name.imageset"
    mkdir -p "$set"
    sips -Z "$PREVIEW_SIZE" "$light" --out "$set/$name-light.png" >/dev/null
    sips -Z "$PREVIEW_SIZE" "$dark" --out "$set/$name-dark.png" >/dev/null

    cat > "$set/Contents.json" <<JSON
{
  "images" : [
    {
      "filename" : "$name-light.png",
      "idiom" : "universal",
      "scale" : "1x"
    },
    {
      "appearances" : [
        {
          "appearance" : "luminosity",
          "value" : "dark"
        }
      ],
      "filename" : "$name-dark.png",
      "idiom" : "universal",
      "scale" : "1x"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
JSON

    rm -rf "$PREVIEWS/$name.imageset"
    mv "$set" "$PREVIEWS/$name.imageset"
done

note "generated ${#PENDING[@]} preview(s)"
